name: Baglisted
main: baglisted.Main
version: 1.0 (alpha)
commands:
  gm:
    description: changes player gamemodes
    usage: /<command>
  ping:
    description: replies with pong
    usage: /<command>
